### ISSUE TITLE
How to get the expert driving data?

### ISSUE THREAD

**Issue by lkhit** [zsdonghao/Imitation-Learning-Dagger-Torcs#1]
Hi!
As for imitation learning, how can we obtain the racing champion or expert driving data?
Thank U!!!

**Comment by zsdonghao** [comment]
in this example, it will generate expert driving data.

**Comment by lkhit** [comment]
@zsdonghao 
Thx very much!

**Comment by lightaime** [comment]
Hi,
I ran you the dagger. But it seems not to converge as you show. Do you have any idea?

Thank you very much!
_______________________________________________________________________
Fuel consumption disabled!
Car damages disabled!
Laptime limit disabled!
Image generation is ON!
Visual Properties Report
------------------------
Compatibility mode, properties unknown.
Waiting for request on port 3101
Client connected on 3101..............
OpenAL backend info:
  Vendor: OpenAL Community
  Renderer: OpenAL Soft
  Version: 1.1 ALSOFT 1.14
  Available sources: 256
  Available buffers: 1024 or more
  Dynamic Sources: requested: 235, created: 235
  #static sources: 21
  #dyn sources   : 235
gfParmSetStr: fopen (config/graph.xml, "wb") failed
sw 64 - sh 64 - vw 64 - vh 64 - imgsize 12288
##################################################
Collecting data from teacher (fake AI) ... 
step: 0
step: 100
step: 200
step: 300
step: 400
step: 500
step: 600
step: 700
step: 800
step: 900
##################################################
Packing data into arrays... 
[!] image/teacher exists ...
2017-10-11 15:48:40.181479: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-11 15:48:40.181508: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-11 15:48:40.181513: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-10-11 15:48:40.181517: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-11 15:48:40.181521: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
  [TL] InputLayer  model/in: (?, 64, 64, 3)
  [TL] Conv2dLayer model/c1/1: shape:[3, 3, 3, 32] strides:[1, 1, 1, 1] pad:VALID act:relu
  [TL] Conv2dLayer model/c1/2: shape:[3, 3, 32, 32] strides:[1, 1, 1, 1] pad:VALID act:relu
  [TL] PoolLayer   model/max1: ksize:[1, 2, 2, 1] strides:[1, 2, 2, 1] padding:VALID pool:max_pool
  [TL] DropoutLayer model/drop1: keep:0.750000 is_fix:True
  [TL] Conv2dLayer model/c2/1: shape:[3, 3, 32, 64] strides:[1, 1, 1, 1] pad:VALID act:relu
  [TL] Conv2dLayer model/c2/2: shape:[3, 3, 64, 64] strides:[1, 1, 1, 1] pad:VALID act:relu
  [TL] PoolLayer   model/max2: ksize:[1, 2, 2, 1] strides:[1, 2, 2, 1] padding:VALID pool:max_pool
  [TL] DropoutLayer model/drop2: keep:0.750000 is_fix:True
  [TL] FlattenLayer model/f: 10816
  [TL] DenseLayer  model/dense1: 512 relu
  [TL] DropoutLayer model/drop3: keep:0.500000 is_fix:True
  [TL] DenseLayer  model/o: 1 tanh
  [TL] InputLayer  model/in: (?, 64, 64, 3)
  [TL] Conv2dLayer model/c1/1: shape:[3, 3, 3, 32] strides:[1, 1, 1, 1] pad:VALID act:relu
  [TL] Conv2dLayer model/c1/2: shape:[3, 3, 32, 32] strides:[1, 1, 1, 1] pad:VALID act:relu
  [TL] PoolLayer   model/max1: ksize:[1, 2, 2, 1] strides:[1, 2, 2, 1] padding:VALID pool:max_pool
  [TL] skip DropoutLayer
  [TL] Conv2dLayer model/c2/1: shape:[3, 3, 32, 64] strides:[1, 1, 1, 1] pad:VALID act:relu
  [TL] Conv2dLayer model/c2/2: shape:[3, 3, 64, 64] strides:[1, 1, 1, 1] pad:VALID act:relu
  [TL] PoolLayer   model/max2: ksize:[1, 2, 2, 1] strides:[1, 2, 2, 1] padding:VALID pool:max_pool
  [TL] skip DropoutLayer
  [TL] FlattenLayer model/f: 10816
  [TL] DenseLayer  model/dense1: 512 relu
  [TL] skip DropoutLayer
  [TL] DenseLayer  model/o: 1 tanh
  [*] geting variables with model

  layer   0: model_1/c1/1/Relu:0  (?, 62, 62, 32)    float32
  layer   1: model_1/c1/2/Relu:0  (?, 60, 60, 32)    float32
  layer   2: model_1/max1:0       (?, 30, 30, 32)    float32
  layer   3: model_1/c2/1/Relu:0  (?, 28, 28, 64)    float32
  layer   4: model_1/c2/2/Relu:0  (?, 26, 26, 64)    float32
  layer   5: model_1/max2:0       (?, 13, 13, 64)    float32
  layer   6: model_1/f:0          (?, 10816)         float32
  layer   7: model_1/dense1/Relu:0 (?, 512)           float32
  layer   8: model_1/o/Tanh:0     (?, 1)             float32

  param   0: model/c1/1/W_conv2d:0 (3, 3, 3, 32)      float32_ref
  param   1: model/c1/1/b_conv2d:0 (32,)              float32_ref
  param   2: model/c1/2/W_conv2d:0 (3, 3, 32, 32)     float32_ref
  param   3: model/c1/2/b_conv2d:0 (32,)              float32_ref
  param   4: model/c2/1/W_conv2d:0 (3, 3, 32, 64)     float32_ref
  param   5: model/c2/1/b_conv2d:0 (64,)              float32_ref
  param   6: model/c2/2/W_conv2d:0 (3, 3, 64, 64)     float32_ref
  param   7: model/c2/2/b_conv2d:0 (64,)              float32_ref
  param   8: model/dense1/W:0     (10816, 512)       float32_ref
  param   9: model/dense1/b:0     (512,)             float32_ref
  param  10: model/o/W:0          (512, 1)           float32_ref
  param  11: model/o/b:0          (1,)               float32_ref
  num of params: 5604385

Epoch [0/100] cost:0.003698 took:5.825152s
Epoch [20/100] cost:0.000582 took:5.622932s
Epoch [40/100] cost:0.000432 took:5.799045s
Epoch [60/100] cost:0.000255 took:6.062013s
Epoch [80/100] cost:0.000180 took:5.915816s
[*] model.npz saved

Fuel consumption disabled!
Car damages disabled!
Laptime limit disabled!
Image generation is ON!
Visual Properties Report
------------------------
Compatibility mode, properties unknown.
Waiting for request on port 3101
Client connected on 3101..............
OpenAL backend info:
  Vendor: OpenAL Community
  Renderer: OpenAL Soft
  Version: 1.1 ALSOFT 1.14
  Available sources: 256
  Available buffers: 1024 or more
  Dynamic Sources: requested: 235, created: 235
  #static sources: 21
  #dyn sources   : 235
gfParmSetStr: fopen (config/graph.xml, "wb") failed
sw 64 - sh 64 - vw 64 - vh 64 - imgsize 12288
##################################################
# Episode: 0 start
******* RESTARTING *****
# step: 59 reward: 676.024040 
##################################################
Epoch [0/100] cost:0.028887 took:6.495797s
Epoch [20/100] cost:0.002082 took:6.561327s
Epoch [40/100] cost:0.001613 took:6.575455s
Epoch [60/100] cost:0.001546 took:6.429398s
Epoch [80/100] cost:0.001411 took:5.362384s
[*] model.npz saved

Fuel consumption disabled!
Car damages disabled!
Laptime limit disabled!
Image generation is ON!
Visual Properties Report
------------------------
Compatibility mode, properties unknown.
Can't open file tracks/oval/backyard4/backyard4.png
Waiting for server on 3101............
Count Down : 5
Waiting for server on 3101............
Count Down : 4
Waiting for server on 3101............
Count Down : 3
Waiting for server on 3101............
Count Down : 2
Waiting for server on 3101............
Count Down : 1
Waiting for server on 3101............
Count Down : 0
Waiting for server on 3101............
Count Down : -1
relaunch torcs

Fuel consumption disabled!
Car damages disabled!
Laptime limit disabled!
Image generation is ON!
Visual Properties Report
------------------------
Compatibility mode, properties unknown.
Waiting for request on port 3101
Waiting for server on 3101............
Count Down : 4
Client connected on 3101..............
OpenAL backend info:
  Vendor: OpenAL Community
  Renderer: OpenAL Soft
  Version: 1.1 ALSOFT 1.14
  Available sources: 256
  Available buffers: 1024 or more
  Dynamic Sources: requested: 235, created: 235
  #static sources: 21
  #dyn sources   : 235
gfParmSetStr: fopen (config/graph.xml, "wb") failed
sw 64 - sh 64 - vw 64 - vh 64 - imgsize 12288
##################################################
# Episode: 1 start
# step: 123 reward: 2868.096669 
##################################################
******* RESTARTING *****
Epoch [0/100] cost:0.032869 took:6.950814s
Epoch [20/100] cost:0.010974 took:7.163207s
Epoch [40/100] cost:0.007635 took:6.996746s
Epoch [60/100] cost:0.006546 took:7.161782s
Epoch [80/100] cost:0.006212 took:7.079982s
[*] model.npz saved

Fuel consumption disabled!
Car damages disabled!
Laptime limit disabled!
Image generation is ON!
Visual Properties Report
------------------------
Compatibility mode, properties unknown.
Waiting for request on port 3101
Client connected on 3101..............
OpenAL backend info:
  Vendor: OpenAL Community
  Renderer: OpenAL Soft
  Version: 1.1 ALSOFT 1.14
  Available sources: 256
  Available buffers: 1024 or more
  Dynamic Sources: requested: 235, created: 235
  #static sources: 21
  #dyn sources   : 235
gfParmSetStr: fopen (config/graph.xml, "wb") failed
sw 64 - sh 64 - vw 64 - vh 64 - imgsize 12288
##################################################
# Episode: 2 start
******* RESTARTING *****
# step: 97 reward: 2603.425093 
##################################################
Epoch [0/100] cost:0.023005 took:7.450832s
Epoch [20/100] cost:0.010528 took:7.712095s
Epoch [40/100] cost:0.009262 took:7.918981s
Epoch [60/100] cost:0.009034 took:7.812006s
Epoch [80/100] cost:0.008439 took:7.668974s
[*] model.npz saved

Fuel consumption disabled!
Car damages disabled!
Laptime limit disabled!
Image generation is ON!
Visual Properties Report
------------------------
Compatibility mode, properties unknown.
Waiting for request on port 3101
Client connected on 3101..............
OpenAL backend info:
  Vendor: OpenAL Community
  Renderer: OpenAL Soft
  Version: 1.1 ALSOFT 1.14
  Available sources: 256
  Available buffers: 1024 or more
  Dynamic Sources: requested: 235, created: 235
  #static sources: 21
  #dyn sources   : 235
gfParmSetStr: fopen (config/graph.xml, "wb") failed
sw 64 - sh 64 - vw 64 - vh 64 - imgsize 12288
##################################################
# Episode: 3 start
******* RESTARTING *****
# step: 96 reward: 2200.940670 
##################################################
Epoch [0/100] cost:0.023130 took:8.187079s
Epoch [20/100] cost:0.011114 took:8.254423s
Epoch [40/100] cost:0.010160 took:8.380528s
Epoch [60/100] cost:0.009290 took:8.476882s
Epoch [80/100] cost:0.009094 took:8.025351s
[*] model.npz saved

Fuel consumption disabled!
Car damages disabled!
Laptime limit disabled!
Image generation is ON!
Visual Properties Report
------------------------
Compatibility mode, properties unknown.
Waiting for request on port 3101
Client connected on 3101..............
OpenAL backend info:
  Vendor: OpenAL Community
  Renderer: OpenAL Soft
  Version: 1.1 ALSOFT 1.14
  Available sources: 256
  Available buffers: 1024 or more
  Dynamic Sources: requested: 235, created: 235
  #static sources: 21
  #dyn sources   : 235
gfParmSetStr: fopen (config/graph.xml, "wb") failed
sw 64 - sh 64 - vw 64 - vh 64 - imgsize 12288
##################################################
# Episode: 4 start
# step: 62 reward: 1187.514918 
##################################################
******* RESTARTING *****
Epoch [0/100] cost:0.025718 took:8.474340s
Epoch [20/100] cost:0.006697 took:8.816665s

**Comment by zsdonghao** [comment]
set you image size to 64x64, by following the readme.
